-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="DNT-UNUSED Minimum of {0} second between each backlash"
			}
		},
		stats={
			[1]="runic_tempering_backlash_cooldown_ms"
		}
	},
	[2]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				text="DNT-UNUSED {0}% increase Damage taken while you have runes"
			},
			[2]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				text="DNT-UNUSED {0}% decrease Damage taken while you have runes"
			}
		},
		stats={
			[1]="runic_tempering_damage_taken_+%"
		}
	},
	[3]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]=1
					}
				},
				text="DNT-UNUSED Each rune can backlash {0} time"
			},
			[2]={
				limit={
					[1]={
						[1]=2,
						[2]="#"
					}
				},
				text="DNT-UNUSED Each rune can backlash {0} times"
			}
		},
		stats={
			[1]="runic_tempering_hit_per_rune"
		}
	},
	[4]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				text="DNT-UNUSED Maximum {0} Runes"
			}
		},
		stats={
			[1]="runic_tempering_max_runes"
		}
	},
	parent="skill_stat_descriptions",
	["runic_tempering_backlash_cooldown_ms"]=1,
	["runic_tempering_damage_taken_+%"]=2,
	["runic_tempering_hit_per_rune"]=3,
	["runic_tempering_max_runes"]=4
}