-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...


itemBases["Rough Greaves"] = {
	type = "Boots",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, ezomyte_basetype = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 22, },
	req = { },
}
itemBases["Iron Greaves"] = {
	type = "Boots",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, ezomyte_basetype = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 47, },
	req = { level = 11, str = 17, },
}
itemBases["Bronze Greaves"] = {
	type = "Boots",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, maraketh_basetype = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 60, },
	req = { level = 16, str = 23, },
}
itemBases["Trimmed Greaves"] = {
	type = "Boots",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, maraketh_basetype = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 87, },
	req = { level = 27, str = 38, },
}
itemBases["Stone Greaves"] = {
	type = "Boots",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, str_armour = true, vaal_basetype = true, },
	implicitModTypes = { },
	armour = { Armour = 102, },
	req = { level = 33, str = 45, },
}
itemBases["Reefsteel Greaves"] = {
	type = "Boots",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, karui_basetype = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 132, },
	req = { level = 45, str = 60, },
}
itemBases["Monument Greaves"] = {
	type = "Boots",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 150, },
	req = { level = 52, str = 69, },
}
itemBases["Totemic Greaves"] = {
	type = "Boots",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 182, },
	req = { level = 65, str = 86, },
}
itemBases["Plated Greaves"] = {
	type = "Boots",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 132, },
	req = { level = 45, str = 60, },
}
itemBases["Lionheart Greaves"] = {
	type = "Boots",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 147, },
	req = { level = 51, str = 68, },
}
itemBases["Elegant Greaves"] = {
	type = "Boots",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 155, },
	req = { level = 54, str = 72, },
}
itemBases["Carved Greaves"] = {
	type = "Boots",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 167, },
	req = { level = 59, str = 78, },
}
itemBases["Bulwark Greaves"] = {
	type = "Boots",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 182, },
	req = { level = 65, str = 86, },
}
itemBases["Ornate Greaves"] = {
	type = "Boots",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 200, },
	req = { level = 70, str = 93, },
}
itemBases["Vaal Greaves"] = {
	type = "Boots",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 219, },
	req = { level = 75, str = 101, },
}
itemBases["Tasalian Greaves"] = {
	type = "Boots",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, karui_basetype = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 237, },
	req = { level = 80, str = 108, },
}

itemBases["Rawhide Boots"] = {
	type = "Boots",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, dex_armour = true, ezomyte_basetype = true, },
	implicitModTypes = { },
	armour = { Evasion = 15, },
	req = { },
}
itemBases["Laced Boots"] = {
	type = "Boots",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, dex_armour = true, ezomyte_basetype = true, },
	implicitModTypes = { },
	armour = { Evasion = 38, },
	req = { level = 11, dex = 17, },
}
itemBases["Embossed Boots"] = {
	type = "Boots",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, dex_armour = true, maraketh_basetype = true, },
	implicitModTypes = { },
	armour = { Evasion = 50, },
	req = { level = 16, dex = 23, },
}
itemBases["Steeltoe Boots"] = {
	type = "Boots",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, dex_armour = true, maraketh_basetype = true, },
	implicitModTypes = { },
	armour = { Evasion = 79, },
	req = { level = 28, dex = 39, },
}
itemBases["Lizardscale Boots"] = {
	type = "Boots",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, dex_armour = true, vaal_basetype = true, },
	implicitModTypes = { },
	armour = { Evasion = 90, },
	req = { level = 33, dex = 45, },
}
itemBases["Flared Boots"] = {
	type = "Boots",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, dex_armour = true, karui_basetype = true, },
	implicitModTypes = { },
	armour = { Evasion = 119, },
	req = { level = 45, dex = 60, },
}
itemBases["Leatherplate Boots"] = {
	type = "Boots",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, dex_armour = true, },
	implicitModTypes = { },
	armour = { Evasion = 135, },
	req = { level = 52, dex = 69, },
}
itemBases["Embroidered Boots"] = {
	type = "Boots",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, dex_armour = true, },
	implicitModTypes = { },
	armour = { Evasion = 166, },
	req = { level = 65, dex = 86, },
}
itemBases["Bound Boots"] = {
	type = "Boots",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, dex_armour = true, },
	implicitModTypes = { },
	armour = { Evasion = 119, },
	req = { level = 45, dex = 60, },
}
itemBases["Sleek Boots"] = {
	type = "Boots",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, dex_armour = true, },
	implicitModTypes = { },
	armour = { Evasion = 133, },
	req = { level = 51, dex = 68, },
}
itemBases["Studded Boots"] = {
	type = "Boots",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, dex_armour = true, },
	implicitModTypes = { },
	armour = { Evasion = 140, },
	req = { level = 54, dex = 72, },
}
itemBases["Serpentscale Boots"] = {
	type = "Boots",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, dex_armour = true, },
	implicitModTypes = { },
	armour = { Evasion = 152, },
	req = { level = 59, dex = 78, },
}
itemBases["Cinched Boots"] = {
	type = "Boots",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, dex_armour = true, },
	implicitModTypes = { },
	armour = { Evasion = 166, },
	req = { level = 65, dex = 86, },
}
itemBases["Cavalry Boots"] = {
	type = "Boots",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, dex_armour = true, },
	implicitModTypes = { },
	armour = { Evasion = 183, },
	req = { level = 70, dex = 93, },
}
itemBases["Dragonscale Boots"] = {
	type = "Boots",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, dex_armour = true, },
	implicitModTypes = { },
	armour = { Evasion = 200, },
	req = { level = 75, dex = 101, },
}
itemBases["Drakeskin Boots"] = {
	type = "Boots",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, dex_armour = true, karui_basetype = true, },
	implicitModTypes = { },
	armour = { Evasion = 216, },
	req = { level = 80, dex = 108, },
}

itemBases["Straw Sandals"] = {
	type = "Boots",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, ezomyte_basetype = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 14, },
	req = { },
}
itemBases["Wrapped Sandals"] = {
	type = "Boots",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, ezomyte_basetype = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 22, },
	req = { level = 11, int = 17, },
}
itemBases["Lattice Sandals"] = {
	type = "Boots",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, int_armour = true, maraketh_basetype = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 25, },
	req = { level = 16, int = 23, },
}
itemBases["Silk Slippers"] = {
	type = "Boots",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, int_armour = true, maraketh_basetype = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 34, },
	req = { level = 27, int = 38, },
}
itemBases["Feathered Sandals"] = {
	type = "Boots",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, int_armour = true, vaal_basetype = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 38, },
	req = { level = 33, int = 45, },
}
itemBases["Flax Sandals"] = {
	type = "Boots",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, int_armour = true, karui_basetype = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 48, },
	req = { level = 45, int = 60, },
}
itemBases["Studded Sandals"] = {
	type = "Boots",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 53, },
	req = { level = 52, int = 69, },
}
itemBases["Elaborate Sandals"] = {
	type = "Boots",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 63, },
	req = { level = 65, int = 86, },
}
itemBases["Laced Sandals"] = {
	type = "Boots",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 48, },
	req = { level = 45, int = 60, },
}
itemBases["Bangled Sandals"] = {
	type = "Boots",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 52, },
	req = { level = 51, int = 68, },
}
itemBases["Elegant Slippers"] = {
	type = "Boots",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 54, },
	req = { level = 54, int = 72, },
}
itemBases["Dunerunner Sandals"] = {
	type = "Boots",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 58, },
	req = { level = 59, int = 78, },
}
itemBases["Bound Sandals"] = {
	type = "Boots",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 63, },
	req = { level = 65, int = 86, },
}
itemBases["Luxurious Slippers"] = {
	type = "Boots",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 69, },
	req = { level = 70, int = 93, },
}
itemBases["Sandsworn Sandals"] = {
	type = "Boots",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 75, },
	req = { level = 75, int = 101, },
}
itemBases["Sekhema Sandals"] = {
	type = "Boots",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, int_armour = true, karui_basetype = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 82, },
	req = { level = 80, int = 108, },
}

itemBases["Mail Sabatons"] = {
	type = "Boots",
	subType = "Armour/Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, ezomyte_basetype = true, str_dex_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 19, Evasion = 15, },
	req = { level = 6, str = 7, dex = 7, },
}
itemBases["Braced Sabatons"] = {
	type = "Boots",
	subType = "Armour/Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, maraketh_basetype = true, str_dex_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 33, Evasion = 28, },
	req = { level = 16, str = 14, dex = 14, },
}
itemBases["Stacked Sabatons"] = {
	type = "Boots",
	subType = "Armour/Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, str_dex_armour = true, vaal_basetype = true, },
	implicitModTypes = { },
	armour = { Armour = 56, Evasion = 50, },
	req = { level = 33, str = 26, dex = 26, },
}
itemBases["Covered Sabatons"] = {
	type = "Boots",
	subType = "Armour/Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, karui_basetype = true, str_dex_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 73, Evasion = 65, },
	req = { level = 45, str = 34, dex = 34, },
}
itemBases["Flexile Sabatons"] = {
	type = "Boots",
	subType = "Armour/Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, str_dex_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 82, Evasion = 74, },
	req = { level = 52, str = 38, dex = 38, },
}
itemBases["Bold Sabatons"] = {
	type = "Boots",
	subType = "Armour/Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, str_dex_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 100, Evasion = 91, },
	req = { level = 65, str = 47, dex = 47, },
}
itemBases["Soldiering Sabatons"] = {
	type = "Boots",
	subType = "Armour/Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, str_dex_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 73, Evasion = 65, },
	req = { level = 45, str = 34, dex = 34, },
}
itemBases["Goldwork Sabatons"] = {
	type = "Boots",
	subType = "Armour/Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, str_dex_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 81, Evasion = 73, },
	req = { level = 51, str = 38, dex = 38, },
}
itemBases["Bastion Sabatons"] = {
	type = "Boots",
	subType = "Armour/Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, str_dex_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 92, Evasion = 84, },
	req = { level = 59, str = 44, dex = 44, },
}
itemBases["Veteran Sabatons"] = {
	type = "Boots",
	subType = "Armour/Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, str_dex_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 100, Evasion = 91, },
	req = { level = 65, str = 47, dex = 47, },
}
itemBases["Noble Sabatons"] = {
	type = "Boots",
	subType = "Armour/Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, str_dex_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 110, Evasion = 101, },
	req = { level = 70, str = 51, dex = 51, },
}
itemBases["Fortress Sabatons"] = {
	type = "Boots",
	subType = "Armour/Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, str_dex_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 120, Evasion = 110, },
	req = { level = 75, str = 56, dex = 56, },
}
itemBases["Blacksteel Sabatons"] = {
	type = "Boots",
	subType = "Armour/Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, karui_basetype = true, str_dex_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 130, Evasion = 119, },
	req = { level = 80, str = 59, dex = 59, },
}

itemBases["Padded Leggings"] = {
	type = "Boots",
	subType = "Armour/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, ezomyte_basetype = true, str_int_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 18, EnergyShield = 9, },
	req = { level = 5, str = 7, int = 7, },
}
itemBases["Secured Leggings"] = {
	type = "Boots",
	subType = "Armour/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, maraketh_basetype = true, str_int_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 33, EnergyShield = 14, },
	req = { level = 16, str = 14, int = 14, },
}
itemBases["Pelt Leggings"] = {
	type = "Boots",
	subType = "Armour/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, str_int_armour = true, vaal_basetype = true, },
	implicitModTypes = { },
	armour = { Armour = 56, EnergyShield = 21, },
	req = { level = 33, str = 26, int = 26, },
}
itemBases["Weaver Leggings"] = {
	type = "Boots",
	subType = "Armour/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, karui_basetype = true, str_int_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 73, EnergyShield = 26, },
	req = { level = 45, str = 34, int = 34, },
}
itemBases["Gilt Leggings"] = {
	type = "Boots",
	subType = "Armour/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, str_int_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 82, EnergyShield = 29, },
	req = { level = 52, str = 38, int = 38, },
}
itemBases["Pious Leggings"] = {
	type = "Boots",
	subType = "Armour/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, str_int_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 100, EnergyShield = 35, },
	req = { level = 65, str = 47, int = 47, },
}
itemBases["Adherent Leggings"] = {
	type = "Boots",
	subType = "Armour/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, str_int_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 73, EnergyShield = 26, },
	req = { level = 45, str = 34, int = 34, },
}
itemBases["Bound Leggings"] = {
	type = "Boots",
	subType = "Armour/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, str_int_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 81, EnergyShield = 29, },
	req = { level = 51, str = 38, int = 38, },
}
itemBases["Shamanistic Leggings"] = {
	type = "Boots",
	subType = "Armour/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, str_int_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 92, EnergyShield = 32, },
	req = { level = 59, str = 44, int = 44, },
}
itemBases["Faithful Leggings"] = {
	type = "Boots",
	subType = "Armour/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, str_int_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 100, EnergyShield = 35, },
	req = { level = 65, str = 47, int = 47, },
}
itemBases["Apostle Leggings"] = {
	type = "Boots",
	subType = "Armour/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, str_int_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 110, EnergyShield = 38, },
	req = { level = 70, str = 51, int = 51, },
}
itemBases["Warlock Leggings"] = {
	type = "Boots",
	subType = "Armour/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, str_int_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 120, EnergyShield = 42, },
	req = { level = 75, str = 56, int = 56, },
}
itemBases["Cryptic Leggings"] = {
	type = "Boots",
	subType = "Armour/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, karui_basetype = true, str_int_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 130, EnergyShield = 45, },
	req = { level = 80, str = 59, int = 59, },
}

itemBases["Frayed Shoes"] = {
	type = "Boots",
	subType = "Evasion/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, dex_int_armour = true, ezomyte_basetype = true, },
	implicitModTypes = { },
	armour = { Evasion = 13, EnergyShield = 9, },
	req = { level = 5, dex = 7, int = 7, },
}
itemBases["Threaded Shoes"] = {
	type = "Boots",
	subType = "Evasion/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, dex_int_armour = true, maraketh_basetype = true, },
	implicitModTypes = { },
	armour = { Evasion = 28, EnergyShield = 14, },
	req = { level = 16, dex = 14, int = 14, },
}
itemBases["Hunting Shoes"] = {
	type = "Boots",
	subType = "Evasion/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, dex_int_armour = true, vaal_basetype = true, },
	implicitModTypes = { },
	armour = { Evasion = 50, EnergyShield = 21, },
	req = { level = 33, dex = 26, int = 26, },
}
itemBases["Steelpoint Shoes"] = {
	type = "Boots",
	subType = "Evasion/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, dex_int_armour = true, karui_basetype = true, },
	implicitModTypes = { },
	armour = { Evasion = 65, EnergyShield = 26, },
	req = { level = 45, dex = 34, int = 34, },
}
itemBases["Velour Shoes"] = {
	type = "Boots",
	subType = "Evasion/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, dex_int_armour = true, },
	implicitModTypes = { },
	armour = { Evasion = 74, EnergyShield = 29, },
	req = { level = 52, dex = 38, int = 38, },
}
itemBases["Bladed Shoes"] = {
	type = "Boots",
	subType = "Evasion/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, dex_int_armour = true, },
	implicitModTypes = { },
	armour = { Evasion = 91, EnergyShield = 35, },
	req = { level = 65, dex = 47, int = 47, },
}
itemBases["Wayfarer Shoes"] = {
	type = "Boots",
	subType = "Evasion/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, dex_int_armour = true, },
	implicitModTypes = { },
	armour = { Evasion = 65, EnergyShield = 26, },
	req = { level = 45, dex = 34, int = 34, },
}
itemBases["Silverbuckled Shoes"] = {
	type = "Boots",
	subType = "Evasion/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, dex_int_armour = true, },
	implicitModTypes = { },
	armour = { Evasion = 73, EnergyShield = 29, },
	req = { level = 51, dex = 38, int = 38, },
}
itemBases["Treerunner Shoes"] = {
	type = "Boots",
	subType = "Evasion/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, dex_int_armour = true, },
	implicitModTypes = { },
	armour = { Evasion = 84, EnergyShield = 32, },
	req = { level = 59, dex = 44, int = 44, },
}
itemBases["Wanderer Shoes"] = {
	type = "Boots",
	subType = "Evasion/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, dex_int_armour = true, },
	implicitModTypes = { },
	armour = { Evasion = 91, EnergyShield = 35, },
	req = { level = 65, dex = 47, int = 47, },
}
itemBases["Charmed Shoes"] = {
	type = "Boots",
	subType = "Evasion/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, dex_int_armour = true, },
	implicitModTypes = { },
	armour = { Evasion = 101, EnergyShield = 38, },
	req = { level = 70, dex = 51, int = 51, },
}
itemBases["Quickslip Shoes"] = {
	type = "Boots",
	subType = "Evasion/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, dex_int_armour = true, },
	implicitModTypes = { },
	armour = { Evasion = 110, EnergyShield = 42, },
	req = { level = 75, dex = 56, int = 56, },
}
itemBases["Daggerfoot Shoes"] = {
	type = "Boots",
	subType = "Evasion/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, dex_int_armour = true, karui_basetype = true, },
	implicitModTypes = { },
	armour = { Evasion = 119, EnergyShield = 45, },
	req = { level = 80, dex = 59, int = 59, },
}

itemBases["Grand Cuisses"] = {
	type = "Boots",
	subType = "Armour/Evasion/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, str_dex_int_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 66, Evasion = 60, EnergyShield = 23, },
	req = { level = 65, str = 34, dex = 34, int = 34, },
}

itemBases["Golden Caligae"] = {
	type = "Boots",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, boots = true, default = true, demigods = true, not_for_sale = true, },
	implicit = "+(8-16)% to all Elemental Resistances",
	implicitModTypes = { { "elemental", "fire", "cold", "lightning", "resistance" }, },
	armour = { },
	req = { level = 12, },
}
