-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...


itemBases["Twig Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, ezomyte_basetype = true, focus = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 12, },
	req = { },
}
itemBases["Woven Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, ezomyte_basetype = true, focus = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 15, },
	req = { level = 6, int = 11, },
}
itemBases["Antler Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, ezomyte_basetype = true, focus = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 17, },
	req = { level = 10, int = 17, },
}
itemBases["Engraved Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, maraketh_basetype = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 21, },
	req = { level = 16, int = 25, },
}
itemBases["Tonal Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, maraketh_basetype = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 25, },
	req = { level = 22, int = 33, },
}
itemBases["Crystal Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, maraketh_basetype = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 28, },
	req = { level = 26, int = 38, },
}
itemBases["Voodoo Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, vaal_basetype = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 32, },
	req = { level = 33, int = 48, },
}
itemBases["Plumed Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, vaal_basetype = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 34, },
	req = { level = 36, int = 52, },
}
itemBases["Runed Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, karui_basetype = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 40, },
	req = { level = 45, int = 64, },
}
itemBases["Whorl Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, karui_basetype = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 43, },
	req = { level = 51, int = 73, },
}
itemBases["Elegant Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 44, },
	req = { level = 52, int = 74, },
}
itemBases["Attuned Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 47, },
	req = { level = 57, int = 81, },
}
itemBases["Magus Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 52, },
	req = { level = 65, int = 91, },
}
itemBases["Wreath Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 40, },
	req = { level = 45, int = 64, },
}
itemBases["Staghorn Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 42, },
	req = { level = 48, int = 69, },
}
itemBases["Jingling Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 43, },
	req = { level = 51, int = 73, },
}
itemBases["Arrayed Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 45, },
	req = { level = 54, int = 77, },
}
itemBases["Cultist Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 49, },
	req = { level = 59, int = 83, },
}
itemBases["Hallowed Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 53, },
	req = { level = 61, int = 86, },
}
itemBases["Druidic Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 58, },
	req = { level = 65, int = 91, },
}
itemBases["Leyline Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 66, },
	req = { level = 70, int = 99, },
}
itemBases["Sacred Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 75, },
	req = { level = 75, int = 107, },
}
itemBases["Tasalian Focus"] = {
	type = "Focus",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, focus = true, int_armour = true, karui_basetype = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 85, },
	req = { level = 80, int = 115, },
}
