-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...


itemBases["Rusted Greathelm"] = {
	type = "Helmet",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, ezomyte_basetype = true, helmet = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 29, },
	req = { },
}
itemBases["Soldier Greathelm"] = {
	type = "Helmet",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, ezomyte_basetype = true, helmet = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 66, },
	req = { level = 12, str = 19, },
}
itemBases["Wrapped Greathelm"] = {
	type = "Helmet",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, maraketh_basetype = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 79, },
	req = { level = 16, str = 25, },
}
itemBases["Spired Greathelm"] = {
	type = "Helmet",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, maraketh_basetype = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 116, },
	req = { level = 27, str = 40, },
}
itemBases["Elite Greathelm"] = {
	type = "Helmet",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_armour = true, vaal_basetype = true, },
	implicitModTypes = { },
	armour = { Armour = 136, },
	req = { level = 33, str = 48, },
}
itemBases["Warrior Greathelm"] = {
	type = "Helmet",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_armour = true, vaal_basetype = true, },
	implicitModTypes = { },
	armour = { Armour = 146, },
	req = { level = 36, str = 52, },
}
itemBases["Commander Greathelm"] = {
	type = "Helmet",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, karui_basetype = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 176, },
	req = { level = 45, str = 64, },
}
itemBases["Fierce Greathelm"] = {
	type = "Helmet",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, karui_basetype = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 196, },
	req = { level = 51, str = 73, },
}
itemBases["Sentinel Greathelm"] = {
	type = "Helmet",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 200, },
	req = { level = 52, str = 74, },
}
itemBases["Goliath Greathelm"] = {
	type = "Helmet",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 216, },
	req = { level = 57, str = 81, },
}
itemBases["Guardian Greathelm"] = {
	type = "Helmet",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 243, },
	req = { level = 65, str = 91, },
}
itemBases["Corroded Greathelm"] = {
	type = "Helmet",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 176, },
	req = { level = 45, str = 64, },
}
itemBases["Mercenary Greathelm"] = {
	type = "Helmet",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 186, },
	req = { level = 48, str = 69, },
}
itemBases["Homeguard Greathelm"] = {
	type = "Helmet",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 196, },
	req = { level = 51, str = 73, },
}
itemBases["Elegant Greathelm"] = {
	type = "Helmet",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 206, },
	req = { level = 54, str = 77, },
}
itemBases["Noble Greathelm"] = {
	type = "Helmet",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 223, },
	req = { level = 59, str = 83, },
}
itemBases["Warmonger Greathelm"] = {
	type = "Helmet",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 243, },
	req = { level = 65, str = 91, },
}
itemBases["Masked Greathelm"] = {
	type = "Helmet",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 267, },
	req = { level = 70, str = 99, },
}
itemBases["Paragon Greathelm"] = {
	type = "Helmet",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 292, },
	req = { level = 75, str = 107, },
}
itemBases["Imperial Greathelm"] = {
	type = "Helmet",
	subType = "Armour",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, karui_basetype = true, str_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 316, },
	req = { level = 80, str = 115, },
}

itemBases["Shabby Hood"] = {
	type = "Helmet",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_armour = true, ezomyte_basetype = true, helmet = true, },
	implicitModTypes = { },
	armour = { Evasion = 19, },
	req = { },
}
itemBases["Felt Cap"] = {
	type = "Helmet",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_armour = true, ezomyte_basetype = true, helmet = true, },
	implicitModTypes = { },
	armour = { Evasion = 48, },
	req = { level = 10, dex = 17, },
}
itemBases["Lace Hood"] = {
	type = "Helmet",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_armour = true, helmet = true, maraketh_basetype = true, },
	implicitModTypes = { },
	armour = { Evasion = 67, },
	req = { level = 16, dex = 25, },
}
itemBases["Swathed Cap"] = {
	type = "Helmet",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_armour = true, helmet = true, maraketh_basetype = true, },
	implicitModTypes = { },
	armour = { Evasion = 98, },
	req = { level = 26, dex = 38, },
}
itemBases["Hunter Hood"] = {
	type = "Helmet",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_armour = true, helmet = true, vaal_basetype = true, },
	implicitModTypes = { },
	armour = { Evasion = 121, },
	req = { level = 33, dex = 48, },
}
itemBases["Viper Cap"] = {
	type = "Helmet",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_armour = true, helmet = true, vaal_basetype = true, },
	implicitModTypes = { },
	armour = { Evasion = 136, },
	req = { level = 38, dex = 54, },
}
itemBases["Corsair Cap"] = {
	type = "Helmet",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_armour = true, helmet = true, karui_basetype = true, },
	implicitModTypes = { },
	armour = { Evasion = 158, },
	req = { level = 45, dex = 64, },
}
itemBases["Leatherbound Hood"] = {
	type = "Helmet",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_armour = true, helmet = true, karui_basetype = true, },
	implicitModTypes = { },
	armour = { Evasion = 174, },
	req = { level = 50, dex = 71, },
}
itemBases["Velvet Cap"] = {
	type = "Helmet",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_armour = true, helmet = true, },
	implicitModTypes = { },
	armour = { Evasion = 181, },
	req = { level = 52, dex = 74, },
}
itemBases["Covert Hood"] = {
	type = "Helmet",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_armour = true, helmet = true, },
	implicitModTypes = { },
	armour = { Evasion = 193, },
	req = { level = 56, dex = 79, },
}
itemBases["Armoured Cap"] = {
	type = "Helmet",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_armour = true, helmet = true, },
	implicitModTypes = { },
	armour = { Evasion = 222, },
	req = { level = 65, dex = 91, },
}
itemBases["Rotted Hood"] = {
	type = "Helmet",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_armour = true, helmet = true, },
	implicitModTypes = { },
	armour = { Evasion = 158, },
	req = { level = 45, dex = 64, },
}
itemBases["Wool Cap"] = {
	type = "Helmet",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_armour = true, helmet = true, },
	implicitModTypes = { },
	armour = { Evasion = 168, },
	req = { level = 48, dex = 69, },
}
itemBases["Narrow Hood"] = {
	type = "Helmet",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_armour = true, helmet = true, },
	implicitModTypes = { },
	armour = { Evasion = 177, },
	req = { level = 51, dex = 73, },
}
itemBases["Wrapped Cap"] = {
	type = "Helmet",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_armour = true, helmet = true, },
	implicitModTypes = { },
	armour = { Evasion = 187, },
	req = { level = 54, dex = 77, },
}
itemBases["Deerstalker Hood"] = {
	type = "Helmet",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_armour = true, helmet = true, },
	implicitModTypes = { },
	armour = { Evasion = 203, },
	req = { level = 59, dex = 83, },
}
itemBases["Woven Cap"] = {
	type = "Helmet",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_armour = true, helmet = true, },
	implicitModTypes = { },
	armour = { Evasion = 222, },
	req = { level = 65, dex = 91, },
}
itemBases["Desert Cap"] = {
	type = "Helmet",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_armour = true, helmet = true, },
	implicitModTypes = { },
	armour = { Evasion = 244, },
	req = { level = 70, dex = 99, },
}
itemBases["Trapper Hood"] = {
	type = "Helmet",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_armour = true, helmet = true, },
	implicitModTypes = { },
	armour = { Evasion = 266, },
	req = { level = 75, dex = 107, },
}
itemBases["Freebooter Cap"] = {
	type = "Helmet",
	subType = "Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_armour = true, helmet = true, karui_basetype = true, },
	implicitModTypes = { },
	armour = { Evasion = 288, },
	req = { level = 80, dex = 115, },
}

itemBases["Twig Circlet"] = {
	type = "Helmet",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, ezomyte_basetype = true, helmet = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 19, },
	req = { },
}
itemBases["Wicker Tiara"] = {
	type = "Helmet",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, ezomyte_basetype = true, helmet = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 28, },
	req = { level = 10, int = 17, },
}
itemBases["Beaded Circlet"] = {
	type = "Helmet",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, int_armour = true, maraketh_basetype = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 34, },
	req = { level = 16, int = 25, },
}
itemBases["Chain Tiara"] = {
	type = "Helmet",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, int_armour = true, maraketh_basetype = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 44, },
	req = { level = 26, int = 38, },
}
itemBases["Feathered Tiara"] = {
	type = "Helmet",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, int_armour = true, vaal_basetype = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 51, },
	req = { level = 33, int = 48, },
}
itemBases["Gold Circlet"] = {
	type = "Helmet",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, int_armour = true, vaal_basetype = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 58, },
	req = { level = 40, int = 58, },
}
itemBases["Vermeil Circlet"] = {
	type = "Helmet",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, int_armour = true, karui_basetype = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 63, },
	req = { level = 45, int = 64, },
}
itemBases["Jade Tiara"] = {
	type = "Helmet",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, int_armour = true, karui_basetype = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 69, },
	req = { level = 50, int = 71, },
}
itemBases["Noble Circlet"] = {
	type = "Helmet",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 71, },
	req = { level = 52, int = 74, },
}
itemBases["Twilight Tiara"] = {
	type = "Helmet",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 77, },
	req = { level = 58, int = 82, },
}
itemBases["Magus Tiara"] = {
	type = "Helmet",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 84, },
	req = { level = 65, int = 91, },
}
itemBases["Druidic Circlet"] = {
	type = "Helmet",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 63, },
	req = { level = 45, int = 64, },
}
itemBases["Avian Tiara"] = {
	type = "Helmet",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 67, },
	req = { level = 48, int = 69, },
}
itemBases["Desert Circlet"] = {
	type = "Helmet",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 70, },
	req = { level = 51, int = 73, },
}
itemBases["Sandsworn Tiara"] = {
	type = "Helmet",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 73, },
	req = { level = 54, int = 77, },
}
itemBases["Jungle Tiara"] = {
	type = "Helmet",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 78, },
	req = { level = 59, int = 83, },
}
itemBases["Skycrown Tiara"] = {
	type = "Helmet",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 84, },
	req = { level = 65, int = 91, },
}
itemBases["Sorcerous Tiara"] = {
	type = "Helmet",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 92, },
	req = { level = 70, int = 99, },
}
itemBases["Kamasan Tiara"] = {
	type = "Helmet",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, int_armour = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 101, },
	req = { level = 75, int = 107, },
}
itemBases["Ancestral Tiara"] = {
	type = "Helmet",
	subType = "Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, int_armour = true, karui_basetype = true, },
	implicitModTypes = { },
	armour = { EnergyShield = 109, },
	req = { level = 80, int = 115, },
}

itemBases["Brimmed Helm"] = {
	type = "Helmet",
	subType = "Armour/Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, ezomyte_basetype = true, helmet = true, str_dex_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 23, Evasion = 18, },
	req = { level = 5, str = 7, dex = 7, },
}
itemBases["Guarded Helm"] = {
	type = "Helmet",
	subType = "Armour/Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, ezomyte_basetype = true, helmet = true, str_dex_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 34, Evasion = 28, },
	req = { level = 11, str = 11, dex = 11, },
}
itemBases["Visored Helm"] = {
	type = "Helmet",
	subType = "Armour/Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, maraketh_basetype = true, str_dex_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 44, Evasion = 37, },
	req = { level = 16, str = 15, dex = 15, },
}
itemBases["Cowled Helm"] = {
	type = "Helmet",
	subType = "Armour/Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, maraketh_basetype = true, str_dex_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 62, Evasion = 54, },
	req = { level = 26, str = 22, dex = 22, },
}
itemBases["Shielded Helm"] = {
	type = "Helmet",
	subType = "Armour/Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_dex_armour = true, vaal_basetype = true, },
	implicitModTypes = { },
	armour = { Armour = 75, Evasion = 66, },
	req = { level = 33, str = 27, dex = 27, },
}
itemBases["Closed Helm"] = {
	type = "Helmet",
	subType = "Armour/Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, karui_basetype = true, str_dex_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 97, Evasion = 87, },
	req = { level = 45, str = 36, dex = 36, },
}
itemBases["Decorated Helm"] = {
	type = "Helmet",
	subType = "Armour/Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_dex_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 110, Evasion = 99, },
	req = { level = 52, str = 41, dex = 41, },
}
itemBases["Gallant Helm"] = {
	type = "Helmet",
	subType = "Armour/Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_dex_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 134, Evasion = 122, },
	req = { level = 65, str = 50, dex = 50, },
}
itemBases["Domed Helm"] = {
	type = "Helmet",
	subType = "Armour/Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_dex_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 97, Evasion = 87, },
	req = { level = 45, str = 36, dex = 36, },
}
itemBases["Engraved Helm"] = {
	type = "Helmet",
	subType = "Armour/Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_dex_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 102, Evasion = 92, },
	req = { level = 48, str = 38, dex = 38, },
}
itemBases["Soldier Helm"] = {
	type = "Helmet",
	subType = "Armour/Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_dex_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 108, Evasion = 98, },
	req = { level = 51, str = 40, dex = 40, },
}
itemBases["Cabalist Helm"] = {
	type = "Helmet",
	subType = "Armour/Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_dex_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 113, Evasion = 103, },
	req = { level = 54, str = 42, dex = 42, },
}
itemBases["Gladiatoral Helm"] = {
	type = "Helmet",
	subType = "Armour/Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_dex_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 123, Evasion = 111, },
	req = { level = 59, str = 46, dex = 46, },
}
itemBases["Warded Helm"] = {
	type = "Helmet",
	subType = "Armour/Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_dex_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 134, Evasion = 122, },
	req = { level = 65, str = 50, dex = 50, },
}
itemBases["Cryptic Helm"] = {
	type = "Helmet",
	subType = "Armour/Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_dex_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 147, Evasion = 134, },
	req = { level = 70, str = 54, dex = 54, },
}
itemBases["Champion Helm"] = {
	type = "Helmet",
	subType = "Armour/Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_dex_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 160, Evasion = 146, },
	req = { level = 75, str = 59, dex = 59, },
}
itemBases["Gladiatorial Helm"] = {
	type = "Helmet",
	subType = "Armour/Evasion",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, karui_basetype = true, str_dex_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 174, Evasion = 159, },
	req = { level = 80, str = 63, dex = 63, },
}

itemBases["Iron Crown"] = {
	type = "Helmet",
	subType = "Armour/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, ezomyte_basetype = true, helmet = true, str_int_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 23, EnergyShield = 12, },
	req = { level = 5, str = 7, int = 7, },
}
itemBases["Horned Crown"] = {
	type = "Helmet",
	subType = "Armour/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, ezomyte_basetype = true, helmet = true, str_int_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 33, EnergyShield = 15, },
	req = { level = 10, str = 10, int = 10, },
}
itemBases["Cultist Crown"] = {
	type = "Helmet",
	subType = "Armour/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, maraketh_basetype = true, str_int_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 44, EnergyShield = 19, },
	req = { level = 16, str = 15, int = 15, },
}
itemBases["Martyr Crown"] = {
	type = "Helmet",
	subType = "Armour/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, maraketh_basetype = true, str_int_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 66, EnergyShield = 25, },
	req = { level = 28, str = 23, int = 23, },
}
itemBases["Heavy Crown"] = {
	type = "Helmet",
	subType = "Armour/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_int_armour = true, vaal_basetype = true, },
	implicitModTypes = { },
	armour = { Armour = 75, EnergyShield = 28, },
	req = { level = 33, str = 27, int = 27, },
}
itemBases["Spiritbone Crown"] = {
	type = "Helmet",
	subType = "Armour/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, karui_basetype = true, str_int_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 97, EnergyShield = 35, },
	req = { level = 45, str = 36, int = 36, },
}
itemBases["Lavish Crown"] = {
	type = "Helmet",
	subType = "Armour/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_int_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 110, EnergyShield = 39, },
	req = { level = 52, str = 41, int = 41, },
}
itemBases["Archon Crown"] = {
	type = "Helmet",
	subType = "Armour/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_int_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 134, EnergyShield = 46, },
	req = { level = 65, str = 50, int = 50, },
}
itemBases["Mailed Crown"] = {
	type = "Helmet",
	subType = "Armour/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_int_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 97, EnergyShield = 35, },
	req = { level = 45, str = 36, int = 36, },
}
itemBases["Forest Crown"] = {
	type = "Helmet",
	subType = "Armour/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_int_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 102, EnergyShield = 37, },
	req = { level = 48, str = 38, int = 38, },
}
itemBases["Zealot Crown"] = {
	type = "Helmet",
	subType = "Armour/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_int_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 108, EnergyShield = 38, },
	req = { level = 51, str = 40, int = 40, },
}
itemBases["Hallowed Crown"] = {
	type = "Helmet",
	subType = "Armour/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_int_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 113, EnergyShield = 40, },
	req = { level = 54, str = 42, int = 42, },
}
itemBases["Inquisitor Crown"] = {
	type = "Helmet",
	subType = "Armour/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_int_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 123, EnergyShield = 43, },
	req = { level = 59, str = 46, int = 46, },
}
itemBases["Druidic Crown"] = {
	type = "Helmet",
	subType = "Armour/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_int_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 134, EnergyShield = 46, },
	req = { level = 65, str = 50, int = 50, },
}
itemBases["Saintly Crown"] = {
	type = "Helmet",
	subType = "Armour/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_int_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 147, EnergyShield = 51, },
	req = { level = 70, str = 54, int = 54, },
}
itemBases["Divine Crown"] = {
	type = "Helmet",
	subType = "Armour/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_int_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 160, EnergyShield = 55, },
	req = { level = 75, str = 59, int = 59, },
}
itemBases["Cryptic Crown"] = {
	type = "Helmet",
	subType = "Armour/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, karui_basetype = true, str_int_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 174, EnergyShield = 60, },
	req = { level = 80, str = 63, int = 63, },
}

itemBases["Hewn Mask"] = {
	type = "Helmet",
	subType = "Evasion/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_int_armour = true, ezomyte_basetype = true, helmet = true, },
	implicitModTypes = { },
	armour = { Evasion = 18, EnergyShield = 12, },
	req = { level = 5, dex = 7, int = 7, },
}
itemBases["Face Mask"] = {
	type = "Helmet",
	subType = "Evasion/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_int_armour = true, ezomyte_basetype = true, helmet = true, },
	implicitModTypes = { },
	armour = { Evasion = 26, EnergyShield = 15, },
	req = { level = 10, dex = 10, int = 10, },
}
itemBases["Hooded Mask"] = {
	type = "Helmet",
	subType = "Evasion/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_int_armour = true, helmet = true, maraketh_basetype = true, },
	implicitModTypes = { },
	armour = { Evasion = 37, EnergyShield = 19, },
	req = { level = 16, dex = 15, int = 15, },
}
itemBases["Veiled Mask"] = {
	type = "Helmet",
	subType = "Evasion/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_int_armour = true, helmet = true, maraketh_basetype = true, },
	implicitModTypes = { },
	armour = { Evasion = 58, EnergyShield = 25, },
	req = { level = 28, dex = 23, int = 23, },
}
itemBases["Tribal Mask"] = {
	type = "Helmet",
	subType = "Evasion/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_int_armour = true, helmet = true, vaal_basetype = true, },
	implicitModTypes = { },
	armour = { Evasion = 66, EnergyShield = 28, },
	req = { level = 33, dex = 27, int = 27, },
}
itemBases["Solid Mask"] = {
	type = "Helmet",
	subType = "Evasion/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_int_armour = true, helmet = true, karui_basetype = true, },
	implicitModTypes = { },
	armour = { Evasion = 87, EnergyShield = 35, },
	req = { level = 45, dex = 36, int = 36, },
}
itemBases["Shaded Mask"] = {
	type = "Helmet",
	subType = "Evasion/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_int_armour = true, helmet = true, },
	implicitModTypes = { },
	armour = { Evasion = 99, EnergyShield = 39, },
	req = { level = 52, dex = 41, int = 41, },
}
itemBases["Death Mask"] = {
	type = "Helmet",
	subType = "Evasion/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_int_armour = true, helmet = true, },
	implicitModTypes = { },
	armour = { Evasion = 122, EnergyShield = 46, },
	req = { level = 65, dex = 50, int = 50, },
}
itemBases["Oak Mask"] = {
	type = "Helmet",
	subType = "Evasion/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_int_armour = true, helmet = true, },
	implicitModTypes = { },
	armour = { Evasion = 87, EnergyShield = 35, },
	req = { level = 45, dex = 36, int = 36, },
}
itemBases["Bandit Mask"] = {
	type = "Helmet",
	subType = "Evasion/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_int_armour = true, helmet = true, },
	implicitModTypes = { },
	armour = { Evasion = 92, EnergyShield = 37, },
	req = { level = 48, dex = 38, int = 38, },
}
itemBases["Skulking Mask"] = {
	type = "Helmet",
	subType = "Evasion/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_int_armour = true, helmet = true, },
	implicitModTypes = { },
	armour = { Evasion = 98, EnergyShield = 38, },
	req = { level = 51, dex = 40, int = 40, },
}
itemBases["Pariah Mask"] = {
	type = "Helmet",
	subType = "Evasion/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_int_armour = true, helmet = true, },
	implicitModTypes = { },
	armour = { Evasion = 103, EnergyShield = 40, },
	req = { level = 54, dex = 42, int = 42, },
}
itemBases["Avian Mask"] = {
	type = "Helmet",
	subType = "Evasion/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_int_armour = true, helmet = true, },
	implicitModTypes = { },
	armour = { Evasion = 111, EnergyShield = 43, },
	req = { level = 59, dex = 46, int = 46, },
}
itemBases["Brigand Mask"] = {
	type = "Helmet",
	subType = "Evasion/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_int_armour = true, helmet = true, },
	implicitModTypes = { },
	armour = { Evasion = 122, EnergyShield = 46, },
	req = { level = 65, dex = 50, int = 50, },
}
itemBases["Faridun Mask"] = {
	type = "Helmet",
	subType = "Evasion/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_int_armour = true, helmet = true, },
	implicitModTypes = { },
	armour = { Evasion = 134, EnergyShield = 51, },
	req = { level = 70, dex = 54, int = 54, },
}
itemBases["Soaring Mask"] = {
	type = "Helmet",
	subType = "Evasion/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_int_armour = true, helmet = true, },
	implicitModTypes = { },
	armour = { Evasion = 146, EnergyShield = 55, },
	req = { level = 75, dex = 59, int = 59, },
}
itemBases["Grinning Mask"] = {
	type = "Helmet",
	subType = "Evasion/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, dex_int_armour = true, helmet = true, karui_basetype = true, },
	implicitModTypes = { },
	armour = { Evasion = 159, EnergyShield = 60, },
	req = { level = 80, dex = 63, int = 63, },
}

itemBases["Grand Visage"] = {
	type = "Helmet",
	subType = "Armour/Evasion/Energy Shield",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, helmet = true, str_dex_int_armour = true, },
	implicitModTypes = { },
	armour = { Armour = 88, Evasion = 80, EnergyShield = 30, },
	req = { level = 65, str = 36, dex = 36, int = 36, },
}

itemBases["Golden Wreath"] = {
	type = "Helmet",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, demigods = true, helmet = true, not_for_sale = true, },
	implicit = "+(16-24) to all Attributes",
	implicitModTypes = { { "attribute" }, },
	armour = { },
	req = { level = 12, },
}
itemBases["Golden Visage"] = {
	type = "Helmet",
	quality = 20,
	socketLimit = 3,
	tags = { armour = true, default = true, demigods = true, helmet = true, not_for_sale = true, },
	implicit = "+(8-16)% to all Elemental Resistances",
	implicitModTypes = { { "elemental", "fire", "cold", "lightning", "resistance" }, },
	armour = { },
	req = { level = 12, },
}
